mina:
  web:
    log:
      enable: true
      excludeUrls:
        - /foo/x/**
        - /v3/api-docs
        - /swagger-resources
        - /druid/**
        - /favicon.ico
      groupName: "aaa"
spring:
  datasource:
    username: root
    password: abcd.1234
    url: jdbc:mysql://localhost:3306/mina?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
---
#启用druid界面监控
spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true