mina:
  web:
    log:
      enable: true
      excludeUrls:
        - /foo/*
        - /v3/api-docs
        - /swagger-resources
      groupName: "aaa"
    auth:
      enable: true
      type: cache
      key: token
      secret: uahsdahsdkjjeriuh
      expireTime: 12
    doc:
      enable: true
  cache:
    redis:
      enable: false
  oss:
    minio:
      enable: true
      endpoint: http://localhost:9000
      accessKey: root
      secretKey: 12345678
      bucketName: minio-demo


