mina:
  web:
    log:
      enable: true
      excludeUrls:
        - /foo/*
        - /v3/api-docs
        - /swagger-resources
      groupName: "aaa"
---
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:9090/xxl-job-admin
    executor:
      appname: mina-boot-xxl-job-executor-sample
      address:
      logpath: job-log
      logretentiondays: 30
mina:
  job:
    xxl:
      admin:
        username: admin
        password: 123456
      executor:
        title: mina-title
---
elasticjob:
  reg-center:
    serverLists: localhost:2181
    namespace: mina-boot

