mina:
  web:
    log:
      enable: false
spring:
  application:
    name: mina-boot-example-admin-client
  boot:
    admin:
      client:
        url: http://localhost:8000
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8088
---
mina:
  boot:
    web:
      response:
        advice: false