logging:
  file:
    path: ./
    name: mina-example-web-config.log
spring:
  application:
    name: mina-config
  profiles:
    active: @active.target.profile@
nacos:
  config:
    server-addr: 127.0.0.1:8848
---
spring:
  config:
    activate:
      on-profile: dev
nacos:
  config:
    namespace: 0efc12c9-8f03-4a24-9e22-18c473db25fa
---
spring:
  config:
    activate:
      on-profile: uat
nacos:
  config:
    namespace: e3fee940-d224-4c48-bf3c-4c086eaaae38
