server:
  port: 8090
spring:
  application:
    name: mina-cloud-example-sentinel

  #  -Dproject.name=mina-cloud-example-sentinel
  #  -Dcsp.sentinel.dashboard.server=localhost:8858
  # 客户端 请求 sentinel dashboard api 端口 (可省略)
#  -Dcsp.sentinel.api.port=8719
#某些环境下本地运行 Dubbo 服务还需要加上-Djava.net.preferIPv4Stack=true
#  -Djava.net.preferIPv4Stack=true
