apiVersion: v1
kind: Service
metadata:
  labels:
    app: mina-boot-example-docker
  name: ks-sample-dev
  namespace: devops-project
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30861
  selector:
    app: mina-boot-example-docker
  sessionAffinity: None
  type: NodePort