apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mina-boot-example-docker
  name: ks-sample-dev
  namespace: mima-project
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: mina-boot-example-docker
  template:
    metadata:
      labels:
        app: mina-boot-example-docker
    spec:
      containers:
        - env:
            - name: CACHE_IGNORE
              value: js|html
            - name: CACHE_PUBLIC_EXPIRATION
              value: 3d
          image: registry.cn-hangzhou.aliyuncs.com/mina-repo/mina-boot-example-docker:v1
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          name: ks-sample
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mina-boot-example-docker
  name: ks-sample-svr
  namespace: mima-project
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30861
  selector:
    app: mina-boot-example-docker
  sessionAffinity: None
  type: NodePort