kind: Deployment
apiVersion: apps/v1
metadata:
  name: mina-devops-test
  namespace: mima-project
  labels:
    app: mina-devops-test

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mina-devops-test
  template:
    metadata:
      labels:
        app: mina-devops-test
    spec:
      containers:
        - name: container-mina-devops-test
          image: 'registry.cn-hangzhou.aliyuncs.com/mina-repo/mina-boot-example-docker:v1'
          ports:
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mina-boot-example-docker
  name: ks-sample-svr
  namespace: mima-project
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30861
  selector:
    app: mina-boot-example-docker
  sessionAffinity: None
  type: NodePort