mina:
  web:
    log:
      enable: true
      exclude-urls:
        - /foo/x/**
        - /v3/api-docs
        - /swagger-resources
        - /favicon.ico
        - /doc.html
        - /webjars/**
      group-name: "mina-boot"
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher