mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 50
      filters: stat
      stat-view-servlet:
        allow: 127.0.0.1
        deny: ''
        enabled: true
        login-password: 123456
        login-username: mina
        reset-enable: false
        url-pattern: /druid/*
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 1000
        url-pattern: /*
    type: com.alibaba.druid.pool.DruidDataSource
