mina:
  web:
    log:
      enable: true
      excludeUrls:
        - /foo/x/**
        - /v3/api-docs
        - /swagger-resources
      groupName: "aaa"
    auth:
      enable: true
      type: cache
      key: token
      secret: uahsdahsdkjjeriuh
      expireTime: 12
    doc:
      enable: true
  cache:
    redis:
      enable: false
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 8
server:
  port: 8089
logging:
  file:
    name: mina-web-example
    path: ./